// Generated by https://quicktype.io

export interface User {
    address:  Address;
    id:       number;
    email:    string;
    username: string;
    password: string;
    name:     Name;
    role?:     string;
    phone:    string;
    __v:      number;
}

export interface Address {
    geolocation: Geolocation;
    city:        string;
    street:      string;
    number:      number;
    zipcode:     string;
}

export interface Geolocation {
    lat:  string;
    long: string;
}

export interface Name {
    firstname: string;
    lastname:  string;
}


export interface NewUser {
    firstName: string;
    email: string;
    role: string;
}